### ISSUE TITLE
Buggy checks

### ISSUE THREAD

**Issue by EmmaRenauld** [StongeEtienne/set-nf#2]
With option nowarp, line 149:

ants_transfo_to_convert: This variable becomes unnecessary, as no warp will be done. However it still checks that the warping files exist.  (output0GenericAffine.mat,output1InverseWarp.nii.gz)

In my case, they don't exist (which is why I'm using nowarp). This check could be skipped.

Also, tractoflow's process PFT_Maps is now PFT_Tracking_Maps (line 157)

I'm still deciphering SET, I might not be right.

**Comment by StongeEtienne** [comment]
This is true,  we could omit the check for "output0GenericAffine.mat,output1InverseWarp.nii.gz" when (params.nowarp == True)
however, the option "--tractoflow" assume that it was run by "Tractoflow" that always include a Warp.
(otherwise, the file is generated but empty for the non-linear and Identity for the affine)

For "PFT_Maps" it depend on Tractoflow version (2.0.1 vs 2.2.1), so yes this could be changed,
but,  Tractoflow-PVE still use the old naming, we would need a way to support both.

**Comment by EmmaRenauld** [comment]
I ran a modified version of tractoflow for the ismrm challenge data, which didn't need a warp. I just copied the T1 directly into T1_warped to skip it, that's why. I understand that it's very specific to my case but considering that it's easy to just remove the check I thought I would tell you.

For the PFT, yeah, I leave you with this challenge ;)

**Comment by StongeEtienne** [comment]
Support for both  "PFT_Maps" or   "PFT_Tracking_Maps" was integrated in https://github.com/StongeEtienne/set-nf/commit/0baa45c343027a42028495b43b3767bd02913dde
